# 中文译文，按正文出现顺序与 items.json 的文本条目一一配对。
# 每对为 (英文前 5 个词, 中文)；build.py 会用前缀校验对齐，错位会直接报错。
# 图注/表注/公式不在此表：图注随原图裁剪呈现，公式为图片。
ZH = [
    ("MobileIE: An Extremely Lightweight and",
     "MobileIE：面向移动设备实时图像增强的极轻量且高效的卷积网络"),
    ("Hailong Yan1, Ao Li1, Xiangtao",
     "Hailong Yan1、Ao Li1、Xiangtao Zhang1、Zhe Liu1、Zenglin Shi2、Ce Zhu1、Le Zhang1*"),
    ("1UESTC 2Hefei University of Technology",
     "1 电子科技大学（UESTC）；2 合肥工业大学。邮箱：yanhailong@std.uestc.edu.cn，lezhang@uestc.edu.cn"),
    ("Abstract",
     "摘要"),
    ("Recent advancements in deep neural",
     "深度神经网络的最新进展推动了图像增强（IE）的大幅提升。然而，由于计算与显存开销巨大，把深度学习模型部署到移动设备这类资源受限的平台上仍然困难。为应对这一挑战并让移动端实时图像增强成为可能，我们提出了一个参数量仅约 4K 的极轻量卷积神经网络（CNN）框架。我们的方法把结构重参数化与增量权重优化（IWO）策略结合起来以保证效率；同时用特征自变换（FST）模块与分层双路注意力（HDPA）机制提升性能，并用局部方差加权（LVW）损失进行优化。借助这一高效框架，我们首次在保证有竞争力画质的同时实现高达 1,100 FPS 的实时图像增强推理，并在多个图像增强任务上取得速度与性能之间的最佳折中。代码将发布于 https://github.com/AVC2-UESTC/MobileIE.git。"),
    ("1. Introduction",
     "1. 引言"),
    ("Image enhancement (IE) aims to",
     "图像增强（IE）的目标是恢复因相机器件局限 [86]、光照不足 [48] 或恶劣环境（例如水下 [55]）而退化的图像。随着智能设备与嵌入式系统日益普及，实时图像增强在移动端等应用中变得不可或缺。这类场景既要求高质量输出，又要求实时处理，因此必须在有限算力约束下完成高效的图像增强 [9, 16–18]。基于 Transformer [14, 42, 69] 与基于扩散模型 [79, 84, 96] 的方法近年在图像增强任务上取得了显著进展，但它们依赖计算代价高昂的自注意力机制和迭代式扩散过程，不适合移动设备。虽然已有工作通过参数压缩与低 FLOPs 架构设计来降低计算复杂度、得到轻量模型 [57, 59, 63, 80, 83]，但这些做法往往牺牲增强质量，难以在种类繁多的退化场景下都保持高性能 [1]。此外，对高分辨率图像日益增长的需求 [69] 进一步加重了移动平台的计算负担。除了算力瓶颈，现有 IE 方法通常只针对特定退化类型优化，泛化能力受限；尽管一些先进算子 [10, 11] 在特定任务上有效，其复杂度使它们难以在移动端部署。因此，设计一个能在资源受限设备上做实时图像增强的通用高效网络，仍然是一个重要的研究挑战。我们认为，面向移动端的图像增强应当在速度与性能之间取得平衡，依靠通用架构与硬件友好算子来实现 [66, 88]。为应对上述挑战，我们提出 MobileIE——一种为资源受限环境下的实时增强设计、同时优化性能与资源占用的方法。尽管退化类型差异很大，各类 IE 任务有着共同的需求：维持结构完整性所需的全局信息，以及精确恢复所需的局部细节。"),
    ("*Corresponding author.",
     "*通讯作者。"),
    ("recovery. This commonality enables the",
     "这种共性使得不同任务可以复用同一套通用模块。基于这一思路，MobileIE 采用精简的拓扑结构与可部署的算子，在资源受限设备上实现高效的性能。我们把训练阶段与推理阶段解耦，简化前向结构以获得更高效的推理。设计核心是 MBRConv——一种多分支重参数化卷积，用不同卷积核尺寸捕获多尺度特征，再经拼接、压缩与映射得到所需的输出维度。此外我们提出特征自变换（FST）模块，通过二阶特征交互捕获非线性关系，从而增强线性卷积的特征表达能力。为了让模型更关注关键区域，我们简化了注意力机制，提出硬件友好的分层双路注意力（HDPA）机制，高效融合全局与局部特征。为克服训练瓶颈，我们提出增量权重优化（IWO）策略与局部方差加权（LVW）损失：IWO 冻结先验知识、将其融入可训练的卷积核并重新参数化为新核以提升性能，LVW 则在不增加参数的前提下提升精度。本文的主要贡献包括：• 我们提出 MobileIE，一个面向移动端实时图像增强的框架，其紧凑高效的模块专为资源受限环境设计。• 我们提出增量权重优化（IWO）策略与局部方差加权（LVW）损失，用于解决紧凑模型训练困难的问题，在不增加复杂度的前提下提升性能。• 我们证明 MobileIE 在三项图像增强任务上同时取得最先进的速度与性能，可持续超过 100 FPS，并能在移动设备上无缝部署。"),
    ("2. Related Works",
     "2. 相关工作"),
    ("2.1. Low-Level Vision Tasks",
     "2.1. 底层视觉任务"),
    ("This section covers three key",
     "本节涵盖三个关键任务：低光增强（LLE）、水下图像增强（UIE）与端到端图像信号处理（ISP）。低光增强。LLE 关注抑制退化图像中的色彩失真与噪声。基于 Retinex 的方法 [5, 46, 78, 81, 85] 通过分离光照与反射分量来增强图像；Zero-DCE [28] 用亮度增强曲线调整曝光不足的图片，PairLIE [26] 从不同光照条件下学习增强。基于 Transformer 的方法 [5, 71, 76] 与基于 Mamba 的方法 [93] 也取得了可观成效；基于扩散模型的方法 [39, 85] 在极暗、含噪且数据有限的条件下仍能生成准确图像。水下图像增强。与传统 UIE 方法 [24, 101] 相比，基于 CNN 的方法 [38, 52, 53, 61] 直接从水下图像学习特征表示。Five A+ [40] 提出带像素注意力模块的两阶段框架以实现实时增强；基于 Transformer [41, 55] 与基于 Mamba [2, 12] 的模型凭借全局感受野更好地处理复杂水下场景；基于扩散模型的方法 [65, 96] 则高效地降噪并增强对比度。图像信号处理。基于学习的 ISP 流程用端到端模型直接把 RAW 输入映射为 RGB 图像，取代传统的多模块流水线。PyNet [35] 聚焦移动端 ISP，MW-ISP [34] 与 AWNet [20] 借助小波变换提升性能；LiteISP [95] 解决 RAW 与 sRGB 之间的错位问题，通过联合学习取得更好结果；Rawformer [56] 用无监督 Transformer 摆脱对成对数据的依赖，DiffRAW [84] 把扩散模型引入 ISP。此外若干 ISP 挑战赛工作 [34, 36, 37] 也取得了可观成果。"),
    ("2.2. Efficient Architectures Design",
     "2.2. 高效架构设计"),
    ("Efficient neural networks aim to",
     "高效神经网络旨在平衡计算复杂度与性能。MobileNet [32]、ShuffleNet [91] 等模型以更少的 FLOPs 取得高性能，GhostNet [29] 与 FasterNet [8] 用低成本运算生成特征图；StarNet [51] 借助星形运算出色地提取丰富表示，VanillaNet [7] 则说明只用少量卷积也能发挥极简主义的力量。此外，重参数化策略在高效网络设计中同样成功：ACNet [21]、DBB [22]、RepVGG [23] 等模型用多分支拓扑加速推理，RepGhost [23]、RepViT [68]、MobileOne [66] 采用类似思路提升性能。多件 NTIRE 挑战赛参赛工作 [15, 45, 60] 也利用重参数化结构来加速高效图像增强任务的推理。"),
    ("3. Proposed Method",
     "3. 本文方法"),
    ("3.1. Overall Pipeline",
     "3.1. 整体流程"),
    ("We aim to design an",
     "我们的目标是设计一个在参数量、速度与性能之间取得平衡的高效图像增强模型。遵循简洁性原则 [88]，我们采用基于基础运算的精简拓扑，如图 2 所示。所提出的 MobileIE 以重参数化为基础，融合四个关键组件：浅层特征提取、深层特征提取、特征变换与注意力机制。训练时，退化图像先经 MBRConv5×5 与 PReLU 激活提取浅层特征；随后由两个 MBRConv3×3 与 FST 模块处理以学习更深层特征；HDPA 机制把模型的注意力导向重要区域，最后由 MBRConv3×3 细化输出。为解决训练性能瓶颈，我们引入 IWO 策略与 LVW 损失函数。推理时，所有 MBRConv 层都被重参数化为标准卷积，在保持性能的同时减少参数量。MobileIE 精简的结构保证了快速推理与便捷的移动端部署。尽管结构简单，如图 1 所示，MobileIE 仍超越了最先进的轻量图像增强模型。"),
    ("3.2. Multi-Branch Re-param Convolution",
     "3.2. 多分支重参数化卷积"),
    ("Re-parameterization has achieved success in",
     "重参数化在高层视觉任务上已取得成功 [21–23]，但直接用于图像增强时效果并不理想 [27]。为此我们提出专为图像增强设计的 MBRConv。图 3(a) 展示了 MBRConv：它包含多个卷积核尺寸不同的并行卷积分支，捕获的多尺度特征经拼接后由一个 Conv1×1（convout）融合。推理时这些分支被重参数化为单个卷积，在保留训练性能的同时降低计算开销。与以往的重参数化方法不同，MBRConv 在每个分支内都放置了并行的 Batch"),
    ("Norm (BN) layers in each",
     "Norm（BN）层。尽管 BN 对图像增强任务的效果有限 [74, 92]，但它能增强非线性，且因其可合并进单个卷积这一独特性质而无法被其他激活替代。并行的 BN 层同时保留平滑后的特征与原始特征，从而提升模型在不同数据分布上的鲁棒性。MBRConv 的更多细节见附录。"),
    ("Although multi-branch topologies assist in",
     "尽管多分支拓扑有助于特征提取，紧凑网络仍然难以学习复杂特征，导致训练后期出现停滞；调整训练超参数往往只能带来微小的提升。为解决这个问题，我们提出增量权重优化（IWO）策略：把可学习权重与先验知识相结合，通过更好地捕获 MBRConv 中层与层之间特征的关系，提升 convout 的融合性能。如图 3(b) 所示，IWO 合并两部分权重：来自先前训练的冻结权重 W_pre，以及可学习权重 W_learn，二者按下式融合："),
    ("where Wpre is the optimal",
     "其中 W_pre 是早期训练得到的最优权重并始终保持冻结，W_learn 在后续训练中被动态更新。最终权重 W_final 作用于拼接后的特征图："),
    ("where xconcat denotes the concatenated",
     "其中 x_concat 表示拼接后的多分支特征，F_conv 表示卷积运算，y_out 与 b_convout 分别表示输出特征图与偏置。W_pre 提供稳定的初始特征表示并尽量减少冗余；W_learn 对这些特征加以细化，提升任务相关细节的捕获能力。IWO 将先验知识与可学习参数结合，在知识迁移与特征细化之间取得平衡，从而改善特征融合。"),
    ("3.3. Feature Self-Transform",
     "3.3. 特征自变换"),
    ("While MBRConv captures multi-scale features,",
     "MBRConv 虽能捕获多尺度特征，但其线性运算限制了高阶特征交互。为此我们提出 FST：它采用二阶交互机制 [51] 来增强模型的非线性表达能力。在 FST 中，输入特征与自身逐元素相乘，再乘以可学习参数 Scale，并加上一个可学习偏置项进行调整。"),
    ("This quadratic interaction captures more",
     "与传统的线性组合不同，这种二次交互能捕获特征之间更复杂的关系；同时按通道施加可学习偏置项，对输出进一步微调。FST 通过捕获高阶交互显著提升特征表示能力，可学习偏置则增强了跨维度的适应性。这一设计在提升表达能力的同时兼顾了计算效率，使 FST 适合轻量模型与实时推理。"),
    ("3.4. Hierarchical Dual-Path Attention",
     "3.4. 分层双路注意力"),
    ("We propose a simple HDPA",
     "我们提出一个简洁的 HDPA 机制来改善图像增强中的特征提取。HDPA 选择性地同时捕获全局与局部特征，融合空间与通道交互，提升特征的精确性与完备性；其双路结构通过两条不同路径在每一层优化特征选择。HDPA 分两步工作：(1) 全局特征提取：用自适应平均池化提取全局统计量，所得全局特征经一个 MBRConv1×1 层与 Sigmoid 激活生成逐通道注意力权重，用以调节每个通道的重要性。该步骤表示为："),
    ("where Ag denotes the global",
     "其中 A_g 表示全局注意力权重，F 表示输入特征。(2) 局部特征增强：第二条路径在全局增强后的特征上使用最大值池化提取局部信息——输入先乘以全局权重 W_g = F ∗ A_g，再做最大值池化以捕获局部信息；局部响应经一个 MBRConv1×1 处理，并由 Sigmoid 激活生成局部注意力权重。"),
    ("where Al represents the local",
     "其中 A_l 表示局部注意力权重。最后，全局与局部注意力权重通过逐元素相乘结合，得到最终注意力特征并作用于输入特征："),
    ("where ˆF donates the output",
     "其中 F̂ 表示经 HDPA 处理后的输出特征。这种双路分层设计在全局上下文与局部特征增强之间取得平衡，同时提升特征提取的深度与精度；其简洁性降低了计算开销，因而非常适合资源受限的环境。"),
    ("3.5. Local Variance Weighted Loss",
     "3.5. 局部方差加权损失"),
    ("Compact CNNs, with limited parameters,",
     "紧凑 CNN 参数有限，难以捕获丰富特征，并且对阻碍优化的极端像素十分敏感 [1, 27]。L1 损失虽然鲁棒，但对所有像素等权，限制了对离群点的处理；L2 强调离群点，却可能造成失衡。为解决这一问题，我们提出局部方差加权损失（LVW）：它能自适应局部的变化程度，并有效缓解离群点的影响。"),
    ("Let {O, L} ∈RB×C×H×W denote",
     "令 {O, L} ∈ R^(B×C×H×W) 分别表示预测输出与真值，其中 B、C、H、W 分别为批量大小、通道数、图像高度与宽度。预测输出与真值在像素 (m, n) 处的绝对差按下式计算："),
    ("For each predicted output, we",
     "对每个预测输出，我们在空间维度 H 与 W 上计算 ∆_(m,n) 的局部均值 µ_(m,n) 与方差 σ²_(m,n)，表示如下："),
    ("To demonstrate the impact of",
     "为说明均值与方差对离群点的影响，我们对同时含有正常值与离群点的模拟数据施加 BN（图 4(a)）。BN 能均衡各样本对均值与方差的贡献，从而降低离群点对分布的影响。基于这些局部统计量，我们为每个像素计算一个加权因子：权重 W_∆ 以误差相对局部均值的绝对偏差进行归一化，并按局部方差进行缩放："),
    ("where ε is a small",
     "其中 ε 是为防止除零而加入的极小常数。施加 Tanh 函数以确保权重保持在有界范围内，并在高方差与低方差区域之间实现平滑过渡。最终损失由 ∆_(m,n) 与对应的局部加权因子相乘得到："),
    ("LLV W dynamically adjusts each",
     "L_LVW 依据局部计算出的权重动态调整每个像素对总损失的贡献，从而把更多的优化力度放在异常像素上。"),
    ("Figure 4(b) illustrates how different",
     "图 4(b) 展示了不同损失函数如何处理像素差异，重点在于它们对预测误差的处理方式。L_LVW 避免了 L2 损失在大误差处的急剧上升，降低了对极端像素的敏感度，同时在小误差处保留足够的梯度响应，在鲁棒性与细节保持之间取得平衡。"),
    ("4. Experiments".replace(chr(8217),chr(39)) if False else "4. Experiments",
     "4. 实验"),
    ("4.1. Experimental Settings".replace(chr(8217),chr(39)) if False else "4.1. Experimental Settings",
     "4.1. 实验设置"),
    ("Implementation Details. We implemented MobileIE".replace(chr(8217),chr(39)) if False else "Implementation Details. We implemented MobileIE",
     "实现细节。我们用 PyTorch 实现 MobileIE。模型使用 Adam 优化器与余弦退火学习率调度，初始学习率 0.001，每 50 个 epoch 重置一次并逐渐衰减。训练前 10 个 epoch 为预热阶段 [30]，学习率固定为 1e-6。模型共训练 2,000 个 epoch，其间引入增量权重优化（IWO）策略以改善收敛。对于 ISP 任务，输入数据被预处理为 256×256 的 Bayer 排布。数据集与指标。LLE 任务使用 LOLv1 [75] 与 LOLv2 [82] 做训练和测试；UIE 与 ISP 任务分别使用 UIEB [43] 与 ZRR [35]。"),
    ("4.2. Quantitative and Visual Comparisons".replace(chr(8217),chr(39)) if False else "4.2. Quantitative and Visual Comparisons",
     "4.2. 定量与可视化对比"),
    ("In this section, we compare the proposed".replace(chr(8217),chr(39)) if False else "In this section, we compare the proposed",
     "本节把 MobileIE 与当前最先进的轻量方法在三项图像增强任务上进行对比，重点关注可视化结果与性能指标。具体使用 PSNR、SSIM、LPIPS 与 SCORE [37] 作为评价指标；计算复杂度在单张 NVIDIA 4090（GPU）与一台搭载骁龙 8 Gen 3 SoC 的智能手机上测得。低光增强：LOLv1 [75] 与 LOLv2 [82] 上的定量结果见表 1。MobileIE 在所有指标上取得更优或相当的 PSNR 与 SSIM，推理速度为 0.895 ms。与轻量 SOTA 方法 IAT [19] 相比，MobileIE 在取得相当 PSNR 增益的同时只用了它 4.7% 的参数量，推理速度快 6.9 倍。"),
    ("Figure 5 shows the visual results, where".replace(chr(8217),chr(39)) if False else "Figure 5 shows the visual results, where",
     "图 5 给出了可视化结果：MobileIE 生成的图像质量更高，与真值非常接近。水下增强：表 2 的定量结果显示 MobileIE 达到 22.81 dB 的 PSNR；值得注意的是，MobileIE 的 PSNR 比 FiveA+ [40] 高 0.3 dB，而参数量只有它的 45%。图 6 的对比表明，与其他轻量方法相比 MobileIE 的色彩恢复更优。ISP：在 ZRR [43] 数据集上，表 3 的定量结果显示 MobileIE 保持了有竞争力的性能，同时推理速度比现有轻量 SOTA 模型快 3 倍，图 7 给出对应的可视化对比。移动端部署：如表 1、2、3 所示，MobileIE 的精简设计（4K 参数、0.924 GFLOPs）使其能在商用移动设备上无缝部署，以超过 100 FPS 实现实时图像增强。这一效率为移动平台上的实时超高清（2K–8K）图像增强铺平了道路。"),
    ("4.3. Ablation Studies and Analyses".replace(chr(8217),chr(39)) if False else "4.3. Ablation Studies and Analyses",
     "4.3. 消融实验与分析"),
    ("We conducted a series of ablation studies".replace(chr(8217),chr(39)) if False else "We conducted a series of ablation studies",
     "我们做了一系列消融实验以验证 MobileIE 各模块的有效性。首先把 MBRConv 与其他重参数化方法 [23, 89, 92] 对比，并把 LVW 损失替换为常规损失函数。如表 4 所示，MBRConv 与 LVW 损失都显著提升了模型性能；更重要的是，MBRConv 在推理时合并为标准卷积，不增加任何计算或显存开销。（1）为什么 MBRConv + IWO 有效？IWO 强化了卷积核骨架。为探究 IWO 对 MBRConv 卷积核的影响，我们可视化了在 UIEB 上训练的 MobileIE 最后一层卷积的权重增量 ∆W。此处 ∆W 定义为使用 IWO 训练得到的权重 W_IWO 与不使用 IWO 的权重 W_base 之差，即 ∆W = W_IWO − W_base。如图 8 所示，大多数 ∆W 数值强化了卷积核中心行与中心列的特征，这有助于模型性能的提升 [6, 21]。"),
    ("IWO reduces channel redundancy, validated by".replace(chr(8217),chr(39)) if False else "IWO reduces channel redundancy, validated by",
     "IWO 降低了通道冗余。我们通过对比 MBRConv5×5 中最后一个 Conv1×1 层在 IWO 优化前后的表现来验证这一点：用 KL（Kullback-Leibler）[6, 73, 100] 散度度量通道相似度，数值越高表示冗余越低。我们在 LOLv1 上训练 MobileIE 并保存不同阶段的检查点，对通道施加 softmax 并计算通道两两之间的 KL 散度，得到不同训练阶段的 KL 矩阵（图 9）。随着训练推进 KL 散度增大，施加 IWO 之后显著上升，说明 MBRConv 在降低冗余、改善特征表示方面有效。IWO 对训练收敛的影响。与预训练阶段类似，W_pre 是前 1000 个 epoch 之后得到的性能良好的权重。由训练曲线（图 10）可见，不使用 IWO 时损失在训练后期停滞，而使用 IWO 时损失继续下降，说明 IWO 促成了权重的进一步优化，提升了模型的收敛性能。曲线中的振荡来自余弦衰减。"),
    ("(2) FST can enhance nonlinear feature".replace(chr(8217),chr(39)) if False else "(2) FST can enhance nonlinear feature",
     "（2）FST 能增强非线性特征交互。FST 使用非线性的平方变换来提升高频敏感度，从而突出图像细节与边缘（图 11）。在傅里叶频谱中，平方运算比 ReLU 表现出更强的高频响应，因而能有效保留细节。可学习参数 Scale 与偏置进一步自适应地调整特征的动态范围，提升恢复性能。"),
    ("Figure 12 shows that the FST achieves".replace(chr(8217),chr(39)) if False else "Figure 12 shows that the FST achieves",
     "图 12 显示，与其他特征变换方法相比，FST 在训练中收敛更快。在最初若干个 epoch 里 FST 就迅速降低损失，说明它能在早期增强特征表示并加速收敛。此外，FST 最终稳定的损失也低于其他方法，体现出它在复杂任务中的鲁棒性与有效性。表 5 进一步证实，在 UIEB [43] 数据集上 FST 取得了最好的特征变换性能。"),
    ("(3) Dual-path fusion enables precise feature".replace(chr(8217),chr(39)) if False else "(3) Dual-path fusion enables precise feature",
     "（3）双路融合实现精确的特征捕获。如何才能既高效又精确地捕获局部与全局特征依赖？遵循"),
    ("Occam’s Razor principle, HDPA adopts".replace(chr(8217),chr(39)) if False else "Occam’s Razor principle, HDPA adopts",
     "奥卡姆剃刀原则，HDPA 采用精简的设计语言，用双路结构与自适应特征交互对特征进行分层分解与聚合，从而在不同尺度上提取关键信息。这种双路设计在反向传播中还能相互优化。"),
    ("Figure 13 illustrates HDPA’s effectiveness. The".replace(chr(8217),chr(39)) if False else "Figure 13 illustrates HDPA’s effectiveness. The",
     "图 13 说明了 HDPA 的有效性。初始卷积保留了关键的边缘与结构，HDPA 热力图则标出了重要区域，把注意力集中在关键细节上，从而得到更锐利的输出特征图，说明 HDPA 的注意力机制通过细化关键细节改善了图像增强效果。"),
    ("Finally, we replaced it with mainstream attention".replace(chr(8217),chr(39)) if False else "Finally, we replaced it with mainstream attention",
     "最后，我们把 HDPA 替换为主流的注意力机制并做消融实验，结果见表 6。在几乎不增加参数（+0.168 K）与 FLOPs（+5.76 M）的情况下，HDPA 带来了 +3.08 dB 的 PSNR 增益。在移动设备上的测试也证实 HDPA 以极低的延迟保持了高效能，凸显了 MobileIE 面向端侧的增强设计在效率上的优势。（4）LVW 在离群点优化上的有效性。我们观察到像素误差直方图近似服从拉普拉斯分布，说明模型主要在优化已经准确的像素，而忽视了离群点 [27]。在 L1 损失的基础上，"),
    ("LVW adjusts weights to increase the constraint".replace(chr(8217),chr(39)) if False else "LVW adjusts weights to increase the constraint",
     "LVW 通过调整权重加大对离群点的约束。归一化把误差标准化，使数据分布更接近均匀，从而保证各像素权重均衡。此外我们可视化了不同损失函数下的像素预测误差直方图（图 14）。LVW 的像素误差均值与中位数都更低，说明它在优化困难区域上更为有效。"),
    ("(5) Module-Wise Lightweight Contributions. Table".replace(chr(8217),chr(39)) if False else "(5) Module-Wise Lightweight Contributions. Table",
     "（5）各模块对轻量化的贡献。表 7 表明，重参数化在推理阶段显著降低了模型复杂度；而 IWO 与 LVW 不引入任何额外开销，适合高效部署。重参数化与这些零代价策略相结合，实现了高效且轻量的推理。"),
    ("5. Conclusion".replace(chr(8217),chr(39)) if False else "5. Conclusion",
     "5. 结论"),
    ("In this paper, we introduce MobileIE, a".replace(chr(8217),chr(39)) if False else "In this paper, we introduce MobileIE, a",
     "本文提出 MobileIE——一个只需 4K 参数、面向移动设备实时图像增强的轻量 CNN。在低光增强、水下增强与图像信号处理三类任务上，MobileIE 同时做到了结构简单与性能出色。MBRConv、特征自变换模块、分层双路注意力机制与局部方差加权损失等关键组件，使 MobileIE 在保持约 0.9 ms 推理耗时的同时取得更优结果。此外，MobileIE 可以方便地部署在任何商用移动设备上，计算开销极小、资源利用高效。未来工作将探索更多优化，把 MobileIE 的应用扩展到更多样的任务。"),
    ("Acknowledgements. This work was supported".replace(chr(8217),chr(39)) if False else "Acknowledgements. This work was supported",
     "致谢。本工作得到国家自然科学基金委科技部国际合作重点专项（项目编号 2024YFE0100700）资助。"),
]

# 图注/表注译文，键为 "figure N" / "table N"。英文图注已在裁剪图内，这里只补中文。
CAPTIONS = {
    "figure 1": "效率对比。MobileIE 在速度、体积与精度之间取得了更好的平衡。",
    "figure 2": "所提 MobileIE 的架构，包含多分支重参数化卷积（MBRConv）、特征自变换（FST）与分层双路注意力（HDPA）。推理时 MBRConv 重参数化为标准卷积，在保持训练性能的同时把模型规模降到 4K 参数。详细架构设置见附录。",
    "figure 3": "MBRConv3×3 的结构。",
    "figure 4": "(a) Batch Norm 对数据分布的影响；(b) 不同损失函数如何处理像素差异。",
    "figure 5": "在 LOLv1 [75] 上低光增强的可视化对比。",
    "figure 6": "在 UIEB [43] 上水下增强的可视化对比。",
    "figure 7": "在 ZRR [35] 上 ISP 的可视化对比。",
    "figure 8": "IWO 优化前后卷积核权重差异的可视化。",
    "figure 9": "不同训练阶段 MBRConv 最后一个卷积层的 KL 相似度矩阵。",
    "figure 10": "训练损失曲线，展示 IWO 对收敛的作用。",
    "figure 11": "各特征变换方法的傅里叶频谱。",
    "figure 12": "不同特征变换方法的训练损失对比。",
    "figure 13": "各阶段特征图与 HDPA 热力图的可视化。",
    "figure 14": "各种损失函数下像素预测误差直方图的可视化。",
    "table 1": "不同低光图像增强模型在 LOL 数据集上的性能对比。SCORE [37] 为性能与效率的综合度量；最优标红、次优标蓝。",
    "table 2": "不同水下图像增强模型在 UIEB 数据集上的性能对比。SCORE [37] 为性能与效率的综合度量；最优标红、次优标蓝。",
    "table 3": "不同图像信号处理模型在 ZRR 数据集上的性能对比。SCORE [37] 为性能与效率的综合度量；最优标红、次优标蓝。",
    "table 4": "损失函数与重参数化模块的性能对比。",
    "table 5": "不同特征变换的性能对比。“Baseline”表示不使用任何特征变换的模型。",
    "table 6": "不同注意力机制在 LOLv1 [75] 数据集上的性能对比。SCORE [37] 反映效率。",
    "table 7": "各模块对轻量化的贡献（效率消融）。",
}
